# ♻ Ecoverse: Smart Waste Intelligence System

![Vercel Deployment](garbage-segregation-wheat.vercel.app)


---

##  Introduction

*Ecoverse* is an intelligent waste management assistant that helps users automatically segregate waste by analyzing images.  
It provides annotated images and insightful visualizations to differentiate between biodegradable and non-biodegradable waste.  
Ecoverse also delivers disposal guidelines, eco-friendly tips, and enables users to download processed images after waste segregation.


##  Features

- 🖼 Annotated image output showing segregated waste categories for user-uploaded images.  
- 📊 Pie chart summarizing the distribution of biodegradable and non-biodegradable waste detected.  
- 📈 Bar graph displaying detection confidence for each identified waste type.  
- ♻ Disposal guidelines and practical eco-friendly tips, tailored based on detected waste.  
- ⬇ Option for users to download the annotated image after segregation analysis.  

---

## Usage

1. *Open the web app:*  
   [https://garbage-segregation-wheat.vercel.app/](https://garbage-segregation-wheat.vercel.app/)

2. *Upload an image* containing mixed waste.

3. *Review* the annotated results and graphs generated by the app.

4. *Check* eco-friendly tips and disposal guidelines on the results page.

5. *Download* the annotated image for your records if desired.

---

##  Tech Stack

| Tech            | Purpose                            |
|-----------------|------------------------------------|
| Node.js + Express | Backend server & API             |
| React.js        | Frontend web interface             |
| Multer          | File upload handling               |
| Axios           | API calls to model server          |
| Canvas          | Image annotation and visualization |
| HuggingFace  | Pre-trained object detection model |
| Vercel          | Deployment                         |